INSERT INTO recipe (rcp_title, rcp_description, rcp_cal, rcp_portion_count) VALUES
('Classic Spaghetti Carbonara', 'Creamy Roman pasta with pancetta and pecorino', 650, 4),
('Vegetarian Lentil Curry', 'Spicy Indian-inspired lentil stew', 420, 6),
('Banana Pancakes', 'Fluffy breakfast pancakes with maple syrup', 320, 3),
('Greek Salad', 'Fresh Mediterranean vegetable salad', 280, 2),
('Beef Chili', 'Hearty Tex-Mex chili con carne', 550, 8),
('Tiramisu', 'Classic Italian coffee dessert', 480, 6),
('Chicken Stir-Fry', 'Quick Asian-style vegetables with rice', 380, 4),
('Vegetable Soup', 'Healthy mixed vegetable broth', 180, 6),
('Homemade Pizza', 'Neapolitan-style margherita pizza', 800, 2),
('Chocolate Mousse', 'Rich French chocolate dessert', 450, 4),
('Salmon Teriyaki', 'Japanese glazed salmon dish', 520, 2),
('Ratatouille', 'Provençal vegetable stew', 220, 4),
('Caesar Salad', 'Classic romaine salad with croutons', 350, 3),
('Beef Bourguignon', 'French red wine beef stew', 680, 6),
('Apple Pie', 'Traditional American dessert', 420, 8),
('Shrimp Scampi', 'Garlic butter shrimp pasta', 580, 3),
('Caprese Salad', 'Italian mozzarella and tomato dish', 310, 2),
('Chicken Curry', 'Creamy Indian-style curry', 490, 4),
('Guacamole', 'Fresh Mexican avocado dip', 250, 4),
('Beef Tacos', 'Crunchy Mexican street food', 480, 4),
('French Onion Soup', 'Caramelized onion broth', 320, 4),
('Cheesecake', 'New York-style baked dessert', 610, 8),
('Pad Thai', 'Thai stir-fried noodles', 540, 3),
('Mushroom Risotto', 'Creamy Italian rice dish', 430, 4),
('Baked Salmon', 'Lemon-dill oven roasted fish', 370, 2),
('Chicken Noodle Soup', 'Comforting classic soup', 290, 6),
('Vegetable Lasagna', 'Meatless pasta bake', 480, 8),
('Pesto Pasta', 'Basil garlic sauce with pine nuts', 520, 3),
('Beef Bulgogi', 'Korean marinated barbecue', 550, 4),
('Greek Yogurt Parfait', 'Layered breakfast dish', 280, 1),
('Chicken Parmesan', 'Breaded Italian chicken', 670, 4),
('Hummus', 'Middle Eastern chickpea dip', 210, 6),
('Pulled Pork Sandwich', 'BBQ slow-cooked pork', 720, 6),
('Falafel', 'Fried chickpea patties', 380, 4),
('Omelette', 'French-style folded eggs', 290, 1),
('Chicken Satay', 'Thai grilled skewers', 410, 4),
('Gazpacho', 'Cold Spanish tomato soup', 190, 4),
('Beef Stroganoff', 'Russian sour cream sauce', 610, 4),
('Panna Cotta', 'Italian cream dessert', 450, 4),
('Fish Tacos', 'Baja-style fried fish', 520, 3),
('Moussaka', 'Greek layered eggplant', 580, 6),
('Pho', 'Vietnamese noodle soup', 480, 4),
('Paella', 'Spanish saffron rice', 670, 6),
('Creme Brulee', 'French custard dessert', 550, 4),
('Lobster Bisque', 'Rich seafood soup', 720, 2),
('Duck Confit', 'French preserved duck', 890, 2),
('Baklava', 'Sweet nut pastry', 480, 12),
('Chicken Tikka Masala', 'British-Indian curry', 610, 4),
('Goulash', 'Hungarian meat stew', 570, 6),
('Sushi Rolls', 'Japanese vinegared rice', 320, 4),
('Borscht', 'Ukrainian beet soup', 310, 6),
('Tandoori Chicken', 'Indian yogurt-marinated', 430, 4),
('Croissants', 'French laminated pastry', 680, 8);