INSERT INTO recipe (rcp_title, rcp_description, rcp_instruction, rcp_cal, rcp_portion_count) VALUES
('Classic Spaghetti Carbonara', 'Creamy Roman pasta with pancetta and pecorino', '1. Cook spaghetti al dente\n2. Fry pancetta until crispy\n3. Mix eggs, cheese and pepper\n4. Combine all ingredients', 650, 4),
('Vegetarian Lentil Curry', 'Spicy Indian-inspired lentil stew', '1. Sauté onions and garlic\n2. Add spices and lentils\n3. Pour coconut milk\n4. Simmer 25 mins', 420, 6),
('Banana Pancakes', 'Fluffy breakfast pancakes with maple syrup', '1. Mash bananas\n2. Mix dry ingredients\n3. Combine wet ingredients\n4. Cook on griddle', 320, 3),
('Greek Salad', 'Fresh Mediterranean vegetable salad', '1. Chop vegetables\n2. Add olives and feta\n3. Dress with olive oil', 280, 2),
('Beef Chili', 'Hearty Tex-Mex chili con carne', '1. Brown beef\n2. Add beans and tomatoes\n3. Season with chili powder\n4. Simmer 1 hour', 550, 8),
('Tiramisu', 'Classic Italian coffee dessert', '1. Make coffee dip\n2. Layer ladyfingers\n3. Whip mascarpone cream\n4. Dust with cocoa', 480, 6),
('Chicken Stir-Fry', 'Quick Asian-style vegetables with rice', '1. Slice chicken\n2. Stir-fry veggies\n3. Add sauce\n4. Serve over rice', 380, 4),
('Vegetable Soup', 'Healthy mixed vegetable broth', '1. Sauté mirepoix\n2. Add stock\n3. Simmer veggies\n4. Season to taste', 180, 6),
('Homemade Pizza', 'Neapolitan-style margherita pizza', '1. Make dough\n2. Top with sauce\n3. Add mozzarella\n4. Bake at 250°C', 800, 2),
('Chocolate Mousse', 'Rich French chocolate dessert', '1. Melt chocolate\n2. Whip cream\n3. Fold together\n4. Chill 4 hours', 450, 4),
('Salmon Teriyaki', 'Japanese glazed salmon dish', '1. Marinate salmon\n2. Grill fish\n3. Reduce sauce\n4. Serve with rice', 520, 2),
('Ratatouille', 'Provençal vegetable stew', '1. Slice vegetables\n2. Layer in dish\n3. Bake 45 mins\n4. Add herbs', 220, 4),
('Caesar Salad', 'Classic romaine salad with croutons', '1. Chop lettuce\n2. Make dressing\n3. Toss with parmesan\n4. Top with chicken', 350, 3),
('Beef Bourguignon', 'French red wine beef stew', '1. Sear beef\n2. Cook vegetables\n3. Deglaze with wine\n4. Braise 3 hours', 680, 6),
('Apple Pie', 'Traditional American dessert', '1. Make crust\n2. Fill with apples\n3. Add spices\n4. Bake 45 mins', 420, 8),
('Shrimp Scampi', 'Garlic butter shrimp pasta', '1. Sauté shrimp\n2. Make sauce\n3. Toss with linguine\n4. Add parsley', 580, 3),
('Caprese Salad', 'Italian mozzarella and tomato dish', '1. Slice tomatoes\n2. Layer with cheese\n3. Add basil\n4. Drizzle balsamic', 310, 2),
('Chicken Curry', 'Creamy Indian-style curry', '1. Brown chicken\n2. Cook spices\n3. Add coconut milk\n4. Simmer 30 mins', 490, 4),
('Guacamole', 'Fresh Mexican avocado dip', '1. Mash avocados\n2. Mix ingredients\n3. Add lime juice\n4. Chill 1 hour', 250, 4),
('Beef Tacos', 'Crunchy Mexican street food', '1. Season beef\n2. Fry tortillas\n3. Assemble toppings\n4. Serve with salsa', 480, 4),
('French Onion Soup', 'Caramelized onion broth', '1. Cook onions\n2. Add broth\n3. Top with bread\n4. Melt cheese', 320, 4),
('Cheesecake', 'New York-style baked dessert', '1. Make crust\n2. Blend filling\n3. Bake in water bath\n4. Chill overnight', 610, 8),
('Pad Thai', 'Thai stir-fried noodles', '1. Soak rice noodles\n2. Fry tofu\n3. Add sauce\n4. Toss with peanuts', 540, 3),
('Mushroom Risotto', 'Creamy Italian rice dish', '1. Sauté mushrooms\n2. Toast rice\n3. Add broth gradually\n4. Stir constantly', 430, 4),
('Baked Salmon', 'Lemon-dill oven roasted fish', '1. Season salmon\n2. Add herbs\n3. Bake 15 mins\n4. Squeeze lemon', 370, 2),
('Chicken Noodle Soup', 'Comforting classic soup', '1. Boil chicken\n2. Add veggies\n3. Cook noodles\n4. Season broth', 290, 6),
('Vegetable Lasagna', 'Meatless pasta bake', '1. Layer noodles\n2. Add ricotta\n3. Roast veggies\n4. Bake 45 mins', 480, 8),
('Pesto Pasta', 'Basil garlic sauce with pine nuts', '1. Blend pesto\n2. Cook pasta\n3. Toss together\n4. Add parmesan', 520, 3),
('Beef Bulgogi', 'Korean marinated barbecue', '1. Slice beef\n2. Make marinade\n3. Grill meat\n4. Serve with rice', 550, 4),
('Greek Yogurt Parfait', 'Layered breakfast dish', '1. Alternate yogurt\n2. Add granola\n3. Top with berries\n4. Drizzle honey', 280, 1),
('Chicken Parmesan', 'Breaded Italian chicken', '1. Pound chicken\n2. Bread cutlets\n3. Fry then bake\n4. Add marinara', 670, 4),
('Hummus', 'Middle Eastern chickpea dip', '1. Blend ingredients\n2. Adjust seasoning\n3. Chill\n4. Serve with pita', 210, 6),
('Pulled Pork Sandwich', 'BBQ slow-cooked pork', '1. Season pork\n2. Slow cook 8h\n3. Shred meat\n4. Serve on bun', 720, 6),
('Falafel', 'Fried chickpea patties', '1. Soak chickpeas\n2. Blend mixture\n3. Form balls\n4. Deep fry', 380, 4),
('Omelette', 'French-style folded eggs', '1. Beat eggs\n2. Cook in pan\n3. Add fillings\n4. Fold carefully', 290, 1),
('Chicken Satay', 'Thai grilled skewers', '1. Marinate chicken\n2. Skewer meat\n3. Grill\n4. Serve with sauce', 410, 4),
('Gazpacho', 'Cold Spanish tomato soup', '1. Blend vegetables\n2. Chill 4h\n3. Add toppings\n4. Serve cold', 190, 4),
('Beef Stroganoff', 'Russian sour cream sauce', '1. Sear beef\n2. Cook mushrooms\n3. Make sauce\n4. Serve with noodles', 610, 4),
('Panna Cotta', 'Italian cream dessert', '1. Heat cream\n2. Add gelatin\n3. Chill in molds\n4. Top berries', 450, 4),
('Fish Tacos', 'Baja-style fried fish', '1. Batter fish\n2. Fry until crisp\n3. Assemble tacos\n4. Add slaw', 520, 3),
('Moussaka', 'Greek layered eggplant', '1. Fry eggplant\n2. Make meat sauce\n3. Layer and bake', 580, 6),
('Pho', 'Vietnamese noodle soup', '1. Simmer broth\n2. Cook noodles\n3. Slice beef\n4. Assemble bowls', 480, 4),
('Paella', 'Spanish saffron rice', '1. Toast rice\n2. Add stock\n3. Cook proteins\n4. Form socarrat', 670, 6),
('Creme Brulee', 'French custard dessert', '1. Make custard\n2. Bake in ramekins\n3. Caramelize sugar top', 550, 4),
('Lobster Bisque', 'Rich seafood soup', '1. Cook lobster\n2. Make stock\n3. Blend soup\n4. Add cream', 720, 2),
('Duck Confit', 'French preserved duck', '1. Salt duck\n2. Cook in fat\n3. Crisp skin\n4. Serve with potatoes', 890, 2),
('Baklava', 'Sweet nut pastry', '1. Layer phyllo\n2. Add nuts\n3. Bake\n4. Soak syrup', 480, 12),
('Chicken Tikka Masala', 'British-Indian curry', '1. Marinate chicken\n2. Grill\n3. Make sauce\n4. Simmer together', 610, 4),
('Goulash', 'Hungarian meat stew', '1. Brown beef\n2. Add paprika\n3. Simmer\n4. Serve with dumplings', 570, 6),
('Sushi Rolls', 'Japanese vinegared rice', '1. Prepare rice\n2. Fill nori\n3. Roll tightly\n4. Slice', 320, 4),
('Borscht', 'Ukrainian beet soup', '1. Cook beets\n2. Add vegetables\n3. Simmer\n4. Serve sour cream', 310, 6),
('Tandoori Chicken', 'Indian yogurt-marinated', '1. Make marinade\n2. Coat chicken\n3. Grill\n4. Serve raita', 430, 4),
('Croissants', 'French laminated pastry', '1. Make dough\n2. Fold butter\n3. Shape\n4. Proof and bake', 680, 8);