/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:27 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS actual_day_meal_adm_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS actual_day_meal CASCADE
;

/* Create Tables */

CREATE TABLE actual_day_meal
(
	adm_id integer NOT NULL   DEFAULT NEXTVAL(('"actual_day_meal_adm_id_seq"'::text)::regclass),
	adm_date date NULL,
	adm_usr_id bigint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE actual_day_meal ADD CONSTRAINT "PK_actual_day_meal"
	PRIMARY KEY (adm_id)
;

CREATE INDEX "IXFK_actual_day_meal_user" ON actual_day_meal (adm_usr_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE actual_day_meal ADD CONSTRAINT "FK_actual_day_meal_user"
	FOREIGN KEY (adm_usr_id) REFERENCES "user" (usr_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE actual_day_meal_adm_id_seq INCREMENT 1 START 1
;