/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:27 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS allergen_alg_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS allergen CASCADE
;

/* Create Tables */

CREATE TABLE allergen
(
	alg_id integer NOT NULL   DEFAULT NEXTVAL(('"allergen_alg_id_seq"'::text)::regclass),
	alg_name varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE allergen ADD CONSTRAINT "PK_allergen"
	PRIMARY KEY (alg_id)
;

CREATE INDEX "IDX_alg_name" ON allergen (alg_name ASC)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE allergen_alg_id_seq INCREMENT 1 START 1
;