/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:18 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS actual_day_meal_adm_id_seq
;

DROP SEQUENCE IF EXISTS allergen_alg_id_seq
;

DROP SEQUENCE IF EXISTS daily_meal_plan_dmp_id_seq
;

DROP SEQUENCE IF EXISTS equipment_eqp_id_seq
;

DROP SEQUENCE IF EXISTS favorite_recipe_fvr_id_seq
;

DROP SEQUENCE IF EXISTS ingredient_ing_id_seq
;

DROP SEQUENCE IF EXISTS ingredient_type_igt_id_seq
;

DROP SEQUENCE IF EXISTS m2m_ing_spl_mis_id_seq
;

DROP SEQUENCE IF EXISTS m2m_rcp_dmp_mrd_id_seq
;

DROP SEQUENCE IF EXISTS m2m_stp_igt_msi_id_seq
;

DROP SEQUENCE IF EXISTS m2m_usr_ing_mui_id_seq
;

DROP SEQUENCE IF EXISTS recipe_rcp_id_seq
;

DROP SEQUENCE IF EXISTS shopping_list_spl_id_seq
;

DROP SEQUENCE IF EXISTS step_stp_id_seq
;

DROP SEQUENCE IF EXISTS user_usr_id_seq
;

DROP SEQUENCE IF EXISTS weakly_meal_plan_wmp_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS actual_day_meal CASCADE
;

DROP TABLE IF EXISTS allergen CASCADE
;

DROP TABLE IF EXISTS daily_meal_plan CASCADE
;

DROP TABLE IF EXISTS equipment CASCADE
;

DROP TABLE IF EXISTS favorite_recipe CASCADE
;

DROP TABLE IF EXISTS image CASCADE
;

DROP TABLE IF EXISTS ingredient CASCADE
;

DROP TABLE IF EXISTS ingredient_type CASCADE
;

DROP TABLE IF EXISTS m2m_ing_adm CASCADE
;

DROP TABLE IF EXISTS m2m_ing_alg CASCADE
;

DROP TABLE IF EXISTS m2m_ing_dmp CASCADE
;

DROP TABLE IF EXISTS m2m_ing_spl CASCADE
;

DROP TABLE IF EXISTS m2m_rcp_adm CASCADE
;

DROP TABLE IF EXISTS m2m_rcp_dmp CASCADE
;

DROP TABLE IF EXISTS m2m_rcp_eqp CASCADE
;

DROP TABLE IF EXISTS m2m_stp_igt CASCADE
;

DROP TABLE IF EXISTS m2m_usr_alg CASCADE
;

DROP TABLE IF EXISTS m2m_usr_eqp CASCADE
;

DROP TABLE IF EXISTS m2m_usr_ing CASCADE
;

DROP TABLE IF EXISTS recipe CASCADE
;

DROP TABLE IF EXISTS shopping_list CASCADE
;

DROP TABLE IF EXISTS step CASCADE
;

DROP TABLE IF EXISTS "user" CASCADE
;

DROP TABLE IF EXISTS weakly_meal_plan CASCADE
;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender_enum') THEN
        EXECUTE 'DROP TYPE gender_enum';
    END IF;
    EXECUTE 'CREATE TYPE gender_enum AS ENUM (''Male'', ''Female'')';
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quantity_enum') THEN
        EXECUTE 'DROP TYPE quantity_enum';
    END IF;
    EXECUTE 'CREATE TYPE quantity_enum AS ENUM (
        ''grams'', 
        ''milliliters'', 
        ''liters'', 
        ''pieces'', 
        ''tablespoons'', 
        ''teaspoons'', 
        ''cups'')';
END $$;

/* Create Tables */

CREATE TABLE actual_day_meal
(
	adm_id integer NOT NULL   DEFAULT NEXTVAL(('"actual_day_meal_adm_id_seq"'::text)::regclass),
	adm_date date NULL,
	adm_usr_id bigint NULL
)
;

CREATE TABLE allergen
(
	alg_id integer NOT NULL   DEFAULT NEXTVAL(('"allergen_alg_id_seq"'::text)::regclass),
	alg_name varchar(100) NOT NULL
)
;

CREATE TABLE daily_meal_plan
(
	dmp_id integer NOT NULL   DEFAULT NEXTVAL(('"daily_meal_plan_dmp_id_seq"'::text)::regclass),
	dmp_date date NULL,
	dmp_cal_day integer NULL,
	dmp_wmp_id integer NULL
)
;

CREATE TABLE equipment
(
	eqp_id integer NOT NULL   DEFAULT NEXTVAL(('"equipment_eqp_id_seq"'::text)::regclass),
	eqp_type varchar(50) NULL,
	eqp_power integer NULL,
	eqp_capacity integer NULL,
	eqp_img_url varchar(256) NULL
)
;

CREATE TABLE favorite_recipe
(
	fvr_id integer NOT NULL   DEFAULT NEXTVAL(('"favorite_recipe_fvr_id_seq"'::text)::regclass),
	fvr_rcp_id integer NULL,
	fvr_usr_id bigint NULL
)
;

CREATE TABLE image
(
	img_id bigint NOT NULL,
	img_url varchar(256) NULL,
	img_stp_id bigint NULL
)
;

CREATE TABLE ingredient
(
	ing_id integer NOT NULL   DEFAULT NEXTVAL(('"ingredient_ing_id_seq"'::text)::regclass),
	ing_name varchar(100) NULL,
	ing_exp_date date NULL,
	ing_weight integer NULL,
	ing_calories integer NULL,
	ing_protein smallint NULL,
	ing_fat smallint NULL,
	ing_hydrates smallint NULL,
	ing_igt_id integer NULL,
	ing_img_url varchar(256) NULL
)
;

CREATE TABLE ingredient_type
(
	igt_id integer NOT NULL   DEFAULT NEXTVAL(('"ingredient_type_igt_id_seq"'::text)::regclass),
	igt_name varchar(150) NULL,
	igt_img_url varchar(256) NULL
)
;

CREATE TABLE m2m_ing_adm
(
	mia_adm_id integer NULL,
	mia_ing_id integer NULL,
	mia_quantity integer NULL,
	mia_quantity_type quantity_enum NULL
)
;

CREATE TABLE m2m_ing_alg
(
	mia_alg_id integer NULL,
	mia_ing_id integer NULL
)
;

CREATE TABLE m2m_ing_dmp
(
	mid_dmp_id integer NULL,
	mid_ing_id integer NULL,
	mid_quantity integer NULL,
	mid_quantity_type quantity_enum NULL
)
;

CREATE TABLE m2m_ing_spl
(
	mis_id integer NOT NULL   DEFAULT NEXTVAL(('"m2m_ing_spl_mis_id_seq"'::text)::regclass),
	mis_quantity integer NULL,
	mis_spl_id integer NOT NULL,
	mis_igt_id integer NOT NULL,
	mis_quantity_type quantity_enum NULL
)
;

CREATE TABLE m2m_rcp_adm
(
	mra_adm_id integer NULL,
	mra_rcp_id integer NULL
)
;

CREATE TABLE m2m_rcp_dmp
(
	mrd_id integer NOT NULL   DEFAULT NEXTVAL(('"m2m_rcp_dmp_mrd_id_seq"'::text)::regclass),
	mrd_rcp_id integer NULL,
	mrd_dmp_id integer NULL
)
;

CREATE TABLE m2m_rcp_eqp
(
	mre_rcp_id integer NULL,
	mre_eqp_id integer NULL
)
;

CREATE TABLE m2m_stp_igt
(
	msi_id integer NOT NULL   DEFAULT NEXTVAL(('"m2m_stp_igt_msi_id_seq"'::text)::regclass),
	msi_igt_id integer NULL,
	msi_quantity integer NULL,
	msi_quantity_type quantity_enum NULL,
	msi_stp_id bigint NOT NULL
)
;

CREATE TABLE m2m_usr_alg
(
	mua_alg_id integer NULL,
	mua_usr_id bigint NULL
)
;

CREATE TABLE m2m_usr_eqp
(
	mue_eqp_id integer NULL,
	mue_usr_id bigint NULL
)
;

CREATE TABLE m2m_usr_ing
(
	mui_id bigint NOT NULL   DEFAULT NEXTVAL(('"m2m_usr_ing_mui_id_seq"'::text)::regclass),
	mui_quantity integer NULL,
	mui_usr_id bigint NULL,
	mui_ing_id integer NULL,
	mui_quantity_type quantity_enum NULL
)
;

CREATE TABLE recipe
(
	rcp_id integer NOT NULL   DEFAULT NEXTVAL(('"recipe_rcp_id_seq"'::text)::regclass),
	rcp_title varchar(300) NULL,
	rcp_description text NULL,
	rcp_cal integer NULL,
	rcp_portion_count smallint NULL
)
;

CREATE TABLE shopping_list
(
	spl_id integer NOT NULL   DEFAULT NEXTVAL(('"shopping_list_spl_id_seq"'::text)::regclass),
	spl_usr_id bigint NULL
)
;

CREATE TABLE step
(
	stp_id bigint NOT NULL   DEFAULT NEXTVAL(('"step_stp_id_seq"'::text)::regclass),
	stp_title varchar(200) NULL,
	stp_instruction text NULL,
	stp_rcp_id integer NOT NULL
)
;

CREATE TABLE "user"
(
	usr_id bigint NOT NULL   DEFAULT NEXTVAL(('"user_usr_id_seq"'::text)::regclass),
	usr_name varchar(100) NULL,
	usr_pas_hash char(32) NULL,
	usr_mail varchar(100) NULL,
	usr_height smallint NULL,
	usr_weight smallint NULL,
	usr_age smallint NULL,
	usr_gender gender_enum NULL,
	usr_cal_day integer NULL
)
;

CREATE TABLE weakly_meal_plan
(
	wmp_id integer NOT NULL   DEFAULT NEXTVAL(('"weakly_meal_plan_wmp_id_seq"'::text)::regclass),
	wmp_start date NULL,
	wmp_end date NULL,
	wmp_usr_id bigint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE actual_day_meal ADD CONSTRAINT "PK_actual_day_meal"
	PRIMARY KEY (adm_id)
;

CREATE INDEX "IXFK_actual_day_meal_user" ON actual_day_meal (adm_usr_id ASC)
;

ALTER TABLE allergen ADD CONSTRAINT "PK_allergen"
	PRIMARY KEY (alg_id)
;

CREATE INDEX "IDX_alg_name" ON allergen (alg_name ASC)
;

ALTER TABLE daily_meal_plan ADD CONSTRAINT "PK_day_meal_plan"
	PRIMARY KEY (dmp_id)
;

CREATE INDEX "IXFK_daily_meal_plan_weakly_meal_plan" ON daily_meal_plan (dmp_wmp_id ASC)
;

ALTER TABLE equipment ADD CONSTRAINT "PK_equipment"
	PRIMARY KEY (eqp_id)
;

ALTER TABLE favorite_recipe ADD CONSTRAINT "PK_favorite_recipe"
	PRIMARY KEY (fvr_id)
;

CREATE INDEX "IXFK_favorite_recipe_recipe" ON favorite_recipe (fvr_rcp_id ASC)
;

CREATE INDEX "IXFK_favorite_recipe_user" ON favorite_recipe (fvr_usr_id ASC)
;

ALTER TABLE image ADD CONSTRAINT "PK_image"
	PRIMARY KEY (img_id)
;

CREATE INDEX "IXFK_image_step" ON image (img_stp_id ASC)
;

ALTER TABLE ingredient ADD CONSTRAINT "PK_ingredient"
	PRIMARY KEY (ing_id)
;

CREATE INDEX "IXFK_ingredient_ingredient_type" ON ingredient (ing_igt_id ASC)
;

ALTER TABLE ingredient_type ADD CONSTRAINT "PK_ingredient_type"
	PRIMARY KEY (igt_id)
;

CREATE INDEX "IXFK_m2m_ing_adm_actual_day_meal" ON m2m_ing_adm (mia_adm_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_adm_ingredient" ON m2m_ing_adm (mia_ing_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_alg_allergen" ON m2m_ing_alg (mia_alg_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_alg_ingredient" ON m2m_ing_alg (mia_ing_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_dmp_daily_meal_plan" ON m2m_ing_dmp (mid_dmp_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_dmp_ingredient" ON m2m_ing_dmp (mid_ing_id ASC)
;

ALTER TABLE m2m_ing_spl ADD CONSTRAINT "PK_m2m_ing_spl"
	PRIMARY KEY (mis_id)
;

CREATE INDEX "IXFK_m2m_ing_spl_ingredient_type" ON m2m_ing_spl (mis_igt_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_spl_shopping_list" ON m2m_ing_spl (mis_spl_id ASC)
;

CREATE INDEX "IXFK_m2m_rcp_adm_actual_day_meal" ON m2m_rcp_adm (mra_adm_id ASC)
;

CREATE INDEX "IXFK_m2m_rcp_adm_recipe" ON m2m_rcp_adm (mra_rcp_id ASC)
;

ALTER TABLE m2m_rcp_dmp ADD CONSTRAINT "PK_m2m_rcp_dmp"
	PRIMARY KEY (mrd_id)
;

CREATE INDEX "IXFK_m2m_rcp_dmp_day_meal_plan" ON m2m_rcp_dmp (mrd_dmp_id ASC)
;

CREATE INDEX "IXFK_m2m_rcp_dmp_recipe" ON m2m_rcp_dmp (mrd_rcp_id ASC)
;

CREATE INDEX "IXFK_m2m_rcp_eqp_equipment" ON m2m_rcp_eqp (mre_eqp_id ASC)
;

CREATE INDEX "IXFK_m2m_rcp_eqp_Recipe" ON m2m_rcp_eqp (mre_rcp_id ASC)
;

ALTER TABLE m2m_stp_igt ADD CONSTRAINT "PK_m2m_recipe_type"
	PRIMARY KEY (msi_id)
;

CREATE INDEX "IXFK_m2m_recipe_type_ingredient_type" ON m2m_stp_igt (msi_igt_id ASC)
;

CREATE INDEX "IXFK_m2m_stp_igt_step" ON m2m_stp_igt (msi_stp_id ASC)
;

CREATE INDEX "IXFK_m2m_usr_alg_allergen" ON m2m_usr_alg (mua_alg_id ASC)
;

CREATE INDEX "IXFK_m2m_usr_alg_user" ON m2m_usr_alg (mua_usr_id ASC)
;

CREATE INDEX "IXFK_m2m_usr_eqp_equipment" ON m2m_usr_eqp (mue_eqp_id ASC)
;

CREATE INDEX "IXFK_m2m_usr_eqp_user" ON m2m_usr_eqp (mue_usr_id ASC)
;

ALTER TABLE m2m_usr_ing ADD CONSTRAINT "PK_m2m_usr_ing"
	PRIMARY KEY (mui_id)
;

CREATE INDEX "IXFK_m2m_usr_ing_ingredient" ON m2m_usr_ing (mui_ing_id ASC)
;

CREATE INDEX "IXFK_m2m_usr_ing_user" ON m2m_usr_ing (mui_usr_id ASC)
;

ALTER TABLE recipe ADD CONSTRAINT "PK_Recipe"
	PRIMARY KEY (rcp_id)
;

ALTER TABLE shopping_list ADD CONSTRAINT "PK_shopping_list"
	PRIMARY KEY (spl_id)
;

CREATE INDEX "IXFK_shopping_list_user" ON shopping_list (spl_usr_id ASC)
;

ALTER TABLE step ADD CONSTRAINT "PK_step"
	PRIMARY KEY (stp_id)
;

CREATE INDEX "IXFK_step_recipe" ON step (stp_rcp_id ASC)
;

ALTER TABLE "user" ADD CONSTRAINT "PK_user"
	PRIMARY KEY (usr_id)
;

ALTER TABLE weakly_meal_plan ADD CONSTRAINT "PK_weakly_meal_plan"
	PRIMARY KEY (wmp_id)
;

CREATE INDEX "IXFK_weakly_meal_plan_user" ON weakly_meal_plan (wmp_usr_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE actual_day_meal ADD CONSTRAINT "FK_actual_day_meal_user"
	FOREIGN KEY (adm_usr_id) REFERENCES "user" (usr_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE daily_meal_plan ADD CONSTRAINT "FK_daily_meal_plan_weakly_meal_plan"
	FOREIGN KEY (dmp_wmp_id) REFERENCES weakly_meal_plan (wmp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE favorite_recipe ADD CONSTRAINT "FK_favorite_recipe_recipe"
	FOREIGN KEY (fvr_rcp_id) REFERENCES recipe (rcp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE favorite_recipe ADD CONSTRAINT "FK_favorite_recipe_user"
	FOREIGN KEY (fvr_usr_id) REFERENCES "user" (usr_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE image ADD CONSTRAINT "FK_image_step"
	FOREIGN KEY (img_stp_id) REFERENCES step (stp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ingredient ADD CONSTRAINT "FK_ingredient_ingredient_type"
	FOREIGN KEY (ing_igt_id) REFERENCES ingredient_type (igt_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_adm ADD CONSTRAINT "FK_m2m_ing_adm_actual_day_meal"
	FOREIGN KEY (mia_adm_id) REFERENCES actual_day_meal (adm_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_adm ADD CONSTRAINT "FK_m2m_ing_adm_ingredient"
	FOREIGN KEY (mia_ing_id) REFERENCES ingredient (ing_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_alg ADD CONSTRAINT "FK_m2m_ing_alg_allergen"
	FOREIGN KEY (mia_alg_id) REFERENCES allergen (alg_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_ing_alg ADD CONSTRAINT "FK_m2m_ing_alg_ingredient"
	FOREIGN KEY (mia_ing_id) REFERENCES ingredient (ing_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_ing_dmp ADD CONSTRAINT "FK_m2m_ing_dmp_daily_meal_plan"
	FOREIGN KEY (mid_dmp_id) REFERENCES daily_meal_plan (dmp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_dmp ADD CONSTRAINT "FK_m2m_ing_dmp_ingredient"
	FOREIGN KEY (mid_ing_id) REFERENCES ingredient (ing_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_spl ADD CONSTRAINT "FK_m2m_ing_spl_ingredient_type"
	FOREIGN KEY (mis_igt_id) REFERENCES ingredient_type (igt_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_spl ADD CONSTRAINT "FK_m2m_ing_spl_shopping_list"
	FOREIGN KEY (mis_spl_id) REFERENCES shopping_list (spl_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_rcp_adm ADD CONSTRAINT "FK_m2m_rcp_adm_actual_day_meal"
	FOREIGN KEY (mra_adm_id) REFERENCES actual_day_meal (adm_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_rcp_adm ADD CONSTRAINT "FK_m2m_rcp_adm_recipe"
	FOREIGN KEY (mra_rcp_id) REFERENCES recipe (rcp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_rcp_dmp ADD CONSTRAINT "FK_m2m_rcp_dmp_day_meal_plan"
	FOREIGN KEY (mrd_dmp_id) REFERENCES daily_meal_plan (dmp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_rcp_dmp ADD CONSTRAINT "FK_m2m_rcp_dmp_recipe"
	FOREIGN KEY (mrd_rcp_id) REFERENCES recipe (rcp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_rcp_eqp ADD CONSTRAINT "FK_m2m_rcp_eqp_equipment"
	FOREIGN KEY (mre_eqp_id) REFERENCES equipment (eqp_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_rcp_eqp ADD CONSTRAINT "FK_m2m_rcp_eqp_Recipe"
	FOREIGN KEY (mre_rcp_id) REFERENCES recipe (rcp_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_stp_igt ADD CONSTRAINT "FK_m2m_recipe_type_ingredient_type"
	FOREIGN KEY (msi_igt_id) REFERENCES ingredient_type (igt_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_stp_igt ADD CONSTRAINT "FK_m2m_stp_igt_step"
	FOREIGN KEY (msi_stp_id) REFERENCES step (stp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_usr_alg ADD CONSTRAINT "FK_m2m_usr_alg_allergen"
	FOREIGN KEY (mua_alg_id) REFERENCES allergen (alg_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_usr_alg ADD CONSTRAINT "FK_m2m_usr_alg_user"
	FOREIGN KEY (mua_usr_id) REFERENCES "user" (usr_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_usr_eqp ADD CONSTRAINT "FK_m2m_usr_eqp_equipment"
	FOREIGN KEY (mue_eqp_id) REFERENCES equipment (eqp_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_usr_eqp ADD CONSTRAINT "FK_m2m_usr_eqp_user"
	FOREIGN KEY (mue_usr_id) REFERENCES "user" (usr_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_usr_ing ADD CONSTRAINT "FK_m2m_usr_ing_ingredient"
	FOREIGN KEY (mui_ing_id) REFERENCES ingredient (ing_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_usr_ing ADD CONSTRAINT "FK_m2m_usr_ing_user"
	FOREIGN KEY (mui_usr_id) REFERENCES "user" (usr_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE shopping_list ADD CONSTRAINT "FK_shopping_list_user"
	FOREIGN KEY (spl_usr_id) REFERENCES "user" (usr_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE step ADD CONSTRAINT "FK_step_recipe"
	FOREIGN KEY (stp_rcp_id) REFERENCES recipe (rcp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE weakly_meal_plan ADD CONSTRAINT "FK_weakly_meal_plan_user"
	FOREIGN KEY (wmp_usr_id) REFERENCES "user" (usr_id) ON DELETE Cascade ON UPDATE Cascade
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE actual_day_meal_adm_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE allergen_alg_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE daily_meal_plan_dmp_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE equipment_eqp_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE favorite_recipe_fvr_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE ingredient_ing_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE ingredient_type_igt_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE m2m_ing_spl_mis_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE m2m_rcp_dmp_mrd_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE m2m_stp_igt_msi_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE m2m_usr_ing_mui_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE recipe_rcp_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE shopping_list_spl_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE step_stp_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE user_usr_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE weakly_meal_plan_wmp_id_seq INCREMENT 1 START 1
;
