/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:28 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS image CASCADE
;

/* Create Tables */

CREATE TABLE image
(
	img_id bigint NOT NULL,
	img_url varchar(256) NULL,
	img_stp_id bigint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE image ADD CONSTRAINT "PK_image"
	PRIMARY KEY (img_id)
;

CREATE INDEX "IXFK_image_step" ON image (img_stp_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE image ADD CONSTRAINT "FK_image_step"
	FOREIGN KEY (img_stp_id) REFERENCES step (stp_id) ON DELETE No Action ON UPDATE No Action
;