/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:28 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS ingredient_ing_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS ingredient CASCADE
;

/* Create Tables */

CREATE TABLE ingredient
(
	ing_id integer NOT NULL   DEFAULT NEXTVAL(('"ingredient_ing_id_seq"'::text)::regclass),
	ing_name varchar(100) NULL,
	ing_exp_date date NULL,
	ing_weight integer NULL,
	ing_calories integer NULL,
	ing_protein smallint NULL,
	ing_fat smallint NULL,
	ing_hydrates smallint NULL,
	ing_igt_id integer NULL,
	ing_img_url varchar(256) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE ingredient ADD CONSTRAINT "PK_ingredient"
	PRIMARY KEY (ing_id)
;

CREATE INDEX "IXFK_ingredient_ingredient_type" ON ingredient (ing_igt_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE ingredient ADD CONSTRAINT "FK_ingredient_ingredient_type"
	FOREIGN KEY (ing_igt_id) REFERENCES ingredient_type (igt_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE ingredient_ing_id_seq INCREMENT 1 START 1
;