/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 16-март-2025 17:44:46 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS ingredient_type_igt_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS ingredient_type CASCADE
;

/* Create Tables */

CREATE TABLE ingredient_type
(
	igt_id integer NOT NULL   DEFAULT NEXTVAL(('"ingredient_type_igt_id_seq"'::text)::regclass),
	igt_name varchar(150) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE ingredient_type ADD CONSTRAINT "PK_ingredient_type"
	PRIMARY KEY (igt_id)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE ingredient_type_igt_id_seq INCREMENT 1 START 1
;