/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:28 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS m2m_stp_igt_msi_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS m2m_stp_igt CASCADE
;

/* Create Tables */

CREATE TABLE m2m_stp_igt
(
	msi_id integer NOT NULL   DEFAULT NEXTVAL(('"m2m_stp_igt_msi_id_seq"'::text)::regclass),
	msi_rcp_id integer NULL,
	msi_igt_id integer NULL,
	msi_quantity integer NULL,
	msi_quantity_type quantity_enum NULL,
	msi_stp_id bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE m2m_stp_igt ADD CONSTRAINT "PK_m2m_recipe_type"
	PRIMARY KEY (msi_id)
;

CREATE INDEX "IXFK_m2m_recipe_type_ingredient_type" ON m2m_stp_igt (msi_igt_id ASC)
;

CREATE INDEX "IXFK_m2m_stp_igt_step" ON m2m_stp_igt (msi_stp_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_stp_igt ADD CONSTRAINT "FK_m2m_recipe_type_ingredient_type"
	FOREIGN KEY (msi_igt_id) REFERENCES ingredient_type (igt_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_stp_igt ADD CONSTRAINT "FK_m2m_stp_igt_step"
	FOREIGN KEY (msi_stp_id) REFERENCES step (stp_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE m2m_stp_igt_msi_id_seq INCREMENT 1 START 1
;