/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:28 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS m2m_ing_dmp CASCADE
;

/* Create Tables */

CREATE TABLE m2m_ing_dmp
(
	mid_dmp_id integer NULL,
	mid_ing_id integer NULL,
	mid_quantity integer NULL,
	mid_quantity_type quantity_enum NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_m2m_ing_dmp_daily_meal_plan" ON m2m_ing_dmp (mid_dmp_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_dmp_ingredient" ON m2m_ing_dmp (mid_ing_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_ing_dmp ADD CONSTRAINT "FK_m2m_ing_dmp_daily_meal_plan"
	FOREIGN KEY (mid_dmp_id) REFERENCES daily_meal_plan (dmp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_dmp ADD CONSTRAINT "FK_m2m_ing_dmp_ingredient"
	FOREIGN KEY (mid_ing_id) REFERENCES ingredient (ing_id) ON DELETE No Action ON UPDATE No Action
;