/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:28 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS m2m_ing_alg CASCADE
;

/* Create Tables */

CREATE TABLE m2m_ing_alg
(
	mia_alg_id integer NULL,
	mia_ing_id integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_m2m_ing_alg_allergen" ON m2m_ing_alg (mia_alg_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_alg_ingredient" ON m2m_ing_alg (mia_ing_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_ing_alg ADD CONSTRAINT "FK_m2m_ing_alg_allergen"
	FOREIGN KEY (mia_alg_id) REFERENCES allergen (alg_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_ing_alg ADD CONSTRAINT "FK_m2m_ing_alg_ingredient"
	FOREIGN KEY (mia_ing_id) REFERENCES ingredient (ing_id) ON DELETE Cascade ON UPDATE Cascade
;