/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 16-март-2025 17:44:46 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS m2m_rcp_eqp CASCADE
;

/* Create Tables */

CREATE TABLE m2m_rcp_eqp
(
	mre_rcp_id integer NULL,
	mre_eqp_id integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_m2m_rcp_eqp_equipment" ON m2m_rcp_eqp (mre_eqp_id ASC)
;

CREATE INDEX "IXFK_m2m_rcp_eqp_Recipe" ON m2m_rcp_eqp (mre_rcp_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_rcp_eqp ADD CONSTRAINT "FK_m2m_rcp_eqp_equipment"
	FOREIGN KEY (mre_eqp_id) REFERENCES equipment (eqp_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_rcp_eqp ADD CONSTRAINT "FK_m2m_rcp_eqp_Recipe"
	FOREIGN KEY (mre_rcp_id) REFERENCES recipe (rcp_id) ON DELETE Cascade ON UPDATE Cascade
;