/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 16-март-2025 17:44:46 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS m2m_ing_adm CASCADE
;

/* Create Tables */

CREATE TABLE m2m_ing_adm
(
	mia_adm_id integer NULL,
	mia_ing_id integer NULL,
	mia_quantity integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_m2m_ing_adm_actual_day_meal" ON m2m_ing_adm (mia_adm_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_adm_ingredient" ON m2m_ing_adm (mia_ing_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_ing_adm ADD CONSTRAINT "FK_m2m_ing_adm_actual_day_meal"
	FOREIGN KEY (mia_adm_id) REFERENCES actual_day_meal (adm_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_adm ADD CONSTRAINT "FK_m2m_ing_adm_ingredient"
	FOREIGN KEY (mia_ing_id) REFERENCES ingredient (ing_id) ON DELETE No Action ON UPDATE No Action
;