/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 16-март-2025 17:44:46 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS m2m_rcp_dmp_mrd_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS m2m_rcp_dmp CASCADE
;

/* Create Tables */

CREATE TABLE m2m_rcp_dmp
(
	mrd_id integer NOT NULL   DEFAULT NEXTVAL(('"m2m_rcp_dmp_mrd_id_seq"'::text)::regclass),
	mrd_rcp_id integer NULL,
	mrd_dmp_id integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE m2m_rcp_dmp ADD CONSTRAINT "PK_m2m_rcp_dmp"
	PRIMARY KEY (mrd_id)
;

CREATE INDEX "IXFK_m2m_rcp_dmp_day_meal_plan" ON m2m_rcp_dmp (mrd_dmp_id ASC)
;

CREATE INDEX "IXFK_m2m_rcp_dmp_recipe" ON m2m_rcp_dmp (mrd_rcp_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_rcp_dmp ADD CONSTRAINT "FK_m2m_rcp_dmp_day_meal_plan"
	FOREIGN KEY (mrd_dmp_id) REFERENCES daily_meal_plan (dmp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_rcp_dmp ADD CONSTRAINT "FK_m2m_rcp_dmp_recipe"
	FOREIGN KEY (mrd_rcp_id) REFERENCES recipe (rcp_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE m2m_rcp_dmp_mrd_id_seq INCREMENT 1 START 1
;