/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:28 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS m2m_ing_spl_mis_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS m2m_ing_spl CASCADE
;

/* Create Tables */

CREATE TABLE m2m_ing_spl
(
	mis_id integer NOT NULL   DEFAULT NEXTVAL(('"m2m_ing_spl_mis_id_seq"'::text)::regclass),
	mis_quantity integer NULL,
	mis_spl_id integer NOT NULL,
	mis_igt_id integer NOT NULL,
	mis_quantity_type quantity_enum NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE m2m_ing_spl ADD CONSTRAINT "PK_m2m_ing_spl"
	PRIMARY KEY (mis_id)
;

CREATE INDEX "IXFK_m2m_ing_spl_ingredient_type" ON m2m_ing_spl (mis_igt_id ASC)
;

CREATE INDEX "IXFK_m2m_ing_spl_shopping_list" ON m2m_ing_spl (mis_spl_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_ing_spl ADD CONSTRAINT "FK_m2m_ing_spl_ingredient_type"
	FOREIGN KEY (mis_igt_id) REFERENCES ingredient_type (igt_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_ing_spl ADD CONSTRAINT "FK_m2m_ing_spl_shopping_list"
	FOREIGN KEY (mis_spl_id) REFERENCES shopping_list (spl_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE m2m_ing_spl_mis_id_seq INCREMENT 1 START 1
;