/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:29 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS m2m_usr_eqp CASCADE
;

/* Create Tables */

CREATE TABLE m2m_usr_eqp
(
	mue_eqp_id integer NULL,
	mue_usr_id bigint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_m2m_usr_eqp_equipment" ON m2m_usr_eqp (mue_eqp_id ASC)
;

CREATE INDEX "IXFK_m2m_usr_eqp_user" ON m2m_usr_eqp (mue_usr_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_usr_eqp ADD CONSTRAINT "FK_m2m_usr_eqp_equipment"
	FOREIGN KEY (mue_eqp_id) REFERENCES equipment (eqp_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_usr_eqp ADD CONSTRAINT "FK_m2m_usr_eqp_user"
	FOREIGN KEY (mue_usr_id) REFERENCES "user" (usr_id) ON DELETE Cascade ON UPDATE Cascade
;