/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:29 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS m2m_usr_ing_mui_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS m2m_usr_ing CASCADE
;

/* Create Tables */

CREATE TABLE m2m_usr_ing
(
	mui_id bigint NOT NULL   DEFAULT NEXTVAL(('"m2m_usr_ing_mui_id_seq"'::text)::regclass),
	mui_quantity integer NULL,
	mui_usr_id bigint NULL,
	mui_ing_id integer NULL,
	mui_quantity_type quantity_enum NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE m2m_usr_ing ADD CONSTRAINT "PK_m2m_usr_ing"
	PRIMARY KEY (mui_id)
;

CREATE INDEX "IXFK_m2m_usr_ing_ingredient" ON m2m_usr_ing (mui_ing_id ASC)
;

CREATE INDEX "IXFK_m2m_usr_ing_user" ON m2m_usr_ing (mui_usr_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_usr_ing ADD CONSTRAINT "FK_m2m_usr_ing_ingredient"
	FOREIGN KEY (mui_ing_id) REFERENCES ingredient (ing_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE m2m_usr_ing ADD CONSTRAINT "FK_m2m_usr_ing_user"
	FOREIGN KEY (mui_usr_id) REFERENCES "user" (usr_id) ON DELETE Cascade ON UPDATE Cascade
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE m2m_usr_ing_mui_id_seq INCREMENT 1 START 1
;