/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:28 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS m2m_rcp_adm CASCADE
;

/* Create Tables */

CREATE TABLE m2m_rcp_adm
(
	mra_adm_id integer NULL,
	mra_rcp_id integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_m2m_rcp_adm_actual_day_meal" ON m2m_rcp_adm (mra_adm_id ASC)
;

CREATE INDEX "IXFK_m2m_rcp_adm_recipe" ON m2m_rcp_adm (mra_rcp_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE m2m_rcp_adm ADD CONSTRAINT "FK_m2m_rcp_adm_actual_day_meal"
	FOREIGN KEY (mra_adm_id) REFERENCES actual_day_meal (adm_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE m2m_rcp_adm ADD CONSTRAINT "FK_m2m_rcp_adm_recipe"
	FOREIGN KEY (mra_rcp_id) REFERENCES recipe (rcp_id) ON DELETE No Action ON UPDATE No Action
;