/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 16-март-2025 17:44:47 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS recipe_rcp_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS recipe CASCADE
;

/* Create Tables */

CREATE TABLE recipe
(
	rcp_id integer NOT NULL   DEFAULT NEXTVAL(('"recipe_rcp_id_seq"'::text)::regclass),
	rcp_title varchar(300) NULL,
	rcp_description text NULL,
	rcp_instruction text NULL,
	rcp_cal integer NULL,
	rcp_portion_count smallint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE recipe ADD CONSTRAINT "PK_Recipe"
	PRIMARY KEY (rcp_id)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE recipe_rcp_id_seq INCREMENT 1 START 1
;