/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 16-март-2025 17:44:47 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS shopping_list_spl_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS shopping_list CASCADE
;

/* Create Tables */

CREATE TABLE shopping_list
(
	spl_id integer NOT NULL   DEFAULT NEXTVAL(('"shopping_list_spl_id_seq"'::text)::regclass),
	spl_usr_id bigint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE shopping_list ADD CONSTRAINT "PK_shopping_list"
	PRIMARY KEY (spl_id)
;

CREATE INDEX "IXFK_shopping_list_user" ON shopping_list (spl_usr_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE shopping_list ADD CONSTRAINT "FK_shopping_list_user"
	FOREIGN KEY (spl_usr_id) REFERENCES "user" (usr_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE shopping_list_spl_id_seq INCREMENT 1 START 1
;