/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:29 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS step_stp_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS step CASCADE
;

/* Create Tables */

CREATE TABLE step
(
	stp_id bigint NOT NULL   DEFAULT NEXTVAL(('"step_stp_id_seq"'::text)::regclass),
	stp_title varchar(200) NULL,
	stp_instruction text NULL,
	stp_rcp_id integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE step ADD CONSTRAINT "PK_step"
	PRIMARY KEY (stp_id)
;

CREATE INDEX "IXFK_step_recipe" ON step (stp_rcp_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE step ADD CONSTRAINT "FK_step_recipe"
	FOREIGN KEY (stp_rcp_id) REFERENCES recipe (rcp_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE step_stp_id_seq INCREMENT 1 START 1
;