/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:29 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS user_usr_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "user" CASCADE
;

/* Create Tables */

CREATE TABLE "user"
(
	usr_id bigint NOT NULL   DEFAULT NEXTVAL(('"user_usr_id_seq"'::text)::regclass),
	usr_name varchar(100) NULL,
	usr_pas_hash char(32) NULL,
	usr_mail varchar(100) NULL,
	usr_height smallint NULL,
	usr_weight smallint NULL,
	usr_age smallint NULL,
	usr_gender gender_enum NULL,
	usr_cal_day integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "user" ADD CONSTRAINT "PK_user"
	PRIMARY KEY (usr_id)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE user_usr_id_seq INCREMENT 1 START 1
;