/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.0 		*/
/*  Created On : 21-март-2025 01:26:29 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS weakly_meal_plan_wmp_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS weakly_meal_plan CASCADE
;

/* Create Tables */

CREATE TABLE weakly_meal_plan
(
	wmp_id integer NOT NULL   DEFAULT NEXTVAL(('"weakly_meal_plan_wmp_id_seq"'::text)::regclass),
	wmp_start date NULL,
	wmp_end date NULL,
	wmp_usr_id bigint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE weakly_meal_plan ADD CONSTRAINT "PK_weakly_meal_plan"
	PRIMARY KEY (wmp_id)
;

CREATE INDEX "IXFK_weakly_meal_plan_user" ON weakly_meal_plan (wmp_usr_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE weakly_meal_plan ADD CONSTRAINT "FK_weakly_meal_plan_user"
	FOREIGN KEY (wmp_usr_id) REFERENCES "user" (usr_id) ON DELETE Cascade ON UPDATE Cascade
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE weakly_meal_plan_wmp_id_seq INCREMENT 1 START 1
;